CREATE TABLE T_REGIONI (
	REG_CODICE int PRIMARY KEY IDENTITY(1,1),
	REG_ISTAT varchar (10) UNIQUE NOT NULL,
	REG_DESCRIZIONE varchar(300) NOT NULL,
	REG_INIZIO_VALIDITA datetime NOT NULL,
	REG_FINE_VALIDITA datetime NOT NULL
)

CREATE TABLE T_PROVINCE (
	PRO_CODICE int PRIMARY KEY IDENTITY(1,1),
	PRO_ISTAT varchar (10) UNIQUE NOT NULL,
	PRO_DESCRIZIONE varchar(300) NOT NULL,
	PRO_INIZIO_VALIDITA datetime NOT NULL,
	PRO_FINE_VALIDITA datetime NOT NULL,
	PRO_REG_CODICE int NOT NULL,
	FOREIGN KEY (PRO_REG_CODICE) REFERENCES T_REGIONI(REG_CODICE)
)

CREATE TABLE T_COMUNI (
	COM_CODICE int PRIMARY KEY IDENTITY(1,1),
	COM_ISTAT varchar (10) UNIQUE NOT NULL,
	COM_DESCRIZIONE varchar(300) NOT NULL,
	COM_INIZIO_VALIDITA datetime NOT NULL,
	COM_FINE_VALIDITA datetime NOT NULL,
	COM_PRO_CODICE int NOT NULL,
	FOREIGN KEY (COM_PRO_CODICE) REFERENCES T_PROVINCE(PRO_CODICE)
)

CREATE TABLE T_UTENTI (
	USER_CODICE bigint PRIMARY KEY IDENTITY(1,1),
	USERNAME varchar(100) NOT NULL UNIQUE,
	SALT varbinary(max) NOT NULL,
	PASSWORD_HASH varbinary(max) NOT NULL,
)

CREATE TABLE T_AUTORIZZAZIONI (
	AUTORIZZAZIONE_CODICE bigint PRIMARY KEY IDENTITY(1,1),
	USER_CODICE bigint NOT NULL,
	NOME_METODO varchar(100),
	FOREIGN KEY (USER_CODICE) REFERENCES USERS(USER_CODICE)
)

CREATE TABLE T_LOG_MESSAGGI (
	LOG_CODICE bigint PRIMARY KEY IDENTITY(1,1),
	LOG_USER bigint NOT NULL,
	LOG_METODO varchar(100) NOT NULL,
	LOG_DATA_ORA datetime NOT NULL,
	LOG_MESSAGGIO_REQUEST varchar(max) NOT NULL,
	LOG_MESSAGGIO_RESPONSE varchar(max) NOT NULL,
	FOREIGN KEY (LOG_USER) REFERENCES USERS(USER_CODICE)
)
